defaults:
  - partitioning: dirichlet
  - model: clmean
  - dataset: cifar10
  - optimizer: adam
  - _self_
general:
  seed: 10
  max_epochs: 30 # maximum number of times we check for correlation
  patience: 5 # for early exit
train_config:
  batch_size: 32
  temperature: 0.2
  num_iterations: 50 # determines how often we check the correlation
  num_client_updates: 1
  fraction_fit: 0.5
  optimized_computation: true # whether we fully simuilate the SL process or run an equivalent but faster computation. The result should be the same
experiment:
  folder: ...
  name: ...
  save_model: false # need to explicitly specify that we should persist the model to the disk
wandb:
  log_to_wandb: false
  loggin_keys:
  - general.seed
  - train_config.batch_size
  - train_config.temperature
  - dataset.dataset_name
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${general.seed}_${dataset.dataset_name}_${train_config.batch_size}_${train_config.temperature}_${train_config.temperature}_${train_config.fraction_fit}_${train_config.num_client_updates}
