defaults:
  - partitioning: dirichlet
  - cem: es
  - dataset: cifar10
  - optimizer: adam
  - model: sup_ae
  - _self_
general:
  seed: 10
train_config:
  batch_size: 32
  cem_evaluation_freq: 30
  fraction_fit: 0.5
  ae_weight: 0.1
  tot_rounds: 1
  proximal_mu: 0.002
wandb:
  log_to_wandb: false
  loggin_keys: []
