defaults:
  - partitioning: dirichlet
  - dataset: cifar10
  - optimizer: adam  # used both for FL training and getting weight difference
  - model: simple_net
  - _self_
profiler: wd
general:
  seed: 10
  eval_iterations: 4
  epochs_per_iteration: 10
train_config:
  batch_size: 32 # used for FL training
profiling:
  ft_epochs: 1
  batch_size: 16
wandb:
  log_to_wandb: false
  loggin_keys: []
experiment:
  folder: ...
  name: ...
strategy:
  fraction_fit: 0.1
  fraction_evaluate: 0.2
  evaluation_frequency: 5
client_resources:
  num_cpus: 2
  num_gpus: 0.125
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${uuid:}
