project: slwr # project name should not have spaces
job_name: "SOTA FL experiment"

code:
  client:
    command: >-
      ./scripts/sh/run_colext.sh python3 scripts/py/run_client.py
      train_config.num_client_updates={{ num_client_updates }}
      train_config.batch_size={{ batch_size }}
      model={{ model }}
      partitioning.num_partitions={{ num_partitions }}

  server:
    command: >-
      ./scripts/sh/run_colext.sh python3 scripts/py/run_server.py
      train_config.fraction_fit={{ fraction_fit }}
      num_rounds={{ num_rounds }}
      model={{ model }}
      train_config.temperature={{ temperature }}
devices:
  - { device_type: JetsonAGXOrin,  count: 1 }
  - { device_type: JetsonOrinNano, count: 3 }
  - { device_type: LattePandaDelta3, count: 4 }
  - { device_type: OrangePi5B, count: 6 }
